### ISSUE TITLE
[Login] OAuth 로그인 API 개발

### ISSUE THREAD

**Issue by kl204** [1Jo-Survey-Management/survey-management-backend#3]
OAuth 로그인 API 개발 이슈입니다.

**Comment by MyeoungDev** [comment]
<img width="926" alt="스크린샷 2023-10-27 오후 2 29 05" src="https://github.com/1Jo-Survey-Management/survey-management-backend/assets/73057935/5a6f2f2f-803c-44a3-b5fe-0195802dc73e">

프론트 로그인과 동일한 상황입니다.  [https://github.com/1Jo-Survey-Management/survey-management-frontend/issues/2](https://github.com/1Jo-Survey-Management/survey-management-frontend/issues/2)
회원가입과 로그인이 아직 완료가 되지 않은 상황인데 DB에 `accessToken` 이 존재합니다.
이 부분도 함께 수정 부탁드립니다.
